### ISSUE TITLE
couldn't find file '../vis/module/header'

### ISSUE THREAD

**Issue by mariowise** [AlexVangelov/vis-rails#2]
Hi! I install the gem but it throws me this error

    couldn't find file '../vis/module/header' under '~/.rvm/gems/ruby-2.1.0/gems/vis-rails-2.0.0/vendor/assets/javascripts' with type 'application/javascript'

To solve it, I went into the gems code and use `//= require_relative` insted of `//= require`. I'm using `Rails 4.1.5`. Regards.

**Comment by AlexVangelov** [comment]
Thank you,
A new vis-rails-2.0.1.gem published with your changes.
Tell me if everything is OK with it.
But this gem needs an update to the latest https://github.com/almende/vis version...
